theme = "tale"
summaryLength="30"
enableRobotsTXT = true
paginate=10

[Author]
  name = "Marcelo Augusto"

[languages]
[languages.pt-br]
  baseURL = "https://gamerforgamer.com/"
  languageCode = 'pt-br'
  contentDir = 'content'
  title = "Gamer For Gamer"
  languageName = "Português"
  weight = 1

[menu]
[[menu.main]]  
  name = 'Free fire'
  url = '/tags/free-fire'
  weight = -10
[[menu.main]]
  name = 'Roblox'
  url = '/tags/roblox'
  weight = -9
[[menu.main]]
  name = 'Elden ring'
  url = '/tags/elden-ring'
  weight = -8
[[menu.main]]
  name = 'Hogwarts Legacy'
  url = '/tags/hogwarts-legacy'
  weight = -6
[[menu.main]]
  name = 'Arena Breakout'
  url = '/tags/arena-breakout'
  weight = -6
[[menu.main]]
  name = 'God of war'
  url = '/tags/god-of-war/'
  weight = -5


[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
