[[redirects]]
    from = "/post/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"
    to = "/noticias/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"