[[redirects]]
    from = "/post/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"
    to = "/noticias/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"
[[redirects]]
    from = "/amazon/pc-gamer/o-mouse-sem-fio-mais-vendido/"
    to = "/amazon/pc-gamer/o-mouse-sem-fio-mais-vendido-mo-285/"

[[redirects]]
    from = "/tags/pc-gaming/"
    to = "/tags/pc-gamer/"

[[redirects]]
    from = "/amazon/pc-gaming/"
    to = "/amazon/pc-gamer/"

[[redirects]]
    from = "/amazon/pc-gaming/*"
    to = "/amazon/pc-gamer/:splat"
    status = 301