[[redirects]]
    from = "/post/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"
    to = "/noticias/elden-ring-teste-agora-mesmo-o-mapa-online-mostra-tudo-que-existe-no-jogo/"
[[redirects]]
    from = "/amazon/pc-gaming/o-mouse-sem-fio-mais-vendido/"
    to = "/amazon/pc-gaming/o-mouse-sem-fio-mais-vendido-mo-285/"