name = "GamerTheme"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://gamerforgamer.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
