name = "Tale"
license = "MIT"
licenselink = "https://github.com/EmielH/tale-hugo/blob/master/LICENSE"
description = "A port of the Tale theme for Hugo. Tale is a minimal Jekyll theme curated for storytellers."
homepage = "https://github.com/EmielH/tale-hugo"
tags = ["minimal", "clean", "responsive", "simple", "personal", "blog", "starter", "light", "typography"]
features = ["pagination"]
min_version = "0.50"
title = "Gamer For Gamer"

[languages]
  [languages.pt-br]
    title = "My New Hugo i18n Site"
    languageName = "Português"
    weight = 1